import type { Metadata } from "next";
import {  Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";


export const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const poppins = Poppins({
  weight: ["400", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} antialiased flex min-h-screen flex-col `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
